### PR TITLE
Optimize _any(_breedon) -> _anybreedon

### PR DESCRIPTION
**Pull request by kodingkoning**

### CODE REVIEW

**Comment by kodingkoning** [comment]
@LaCuneta I am not starting a PR on the main branch yet because I am still getting an error when testing this optimization, but I wondered if you could take a look at this error. I'm unable to reference "breedName" from `_breedon`, which is required to optimize for the appropriate breed. After optimizing `_anyturtleson` I expected this optimization to be straightforward.

Error:

```
[info] - models/3D/Sample Models/Hydrogen Diffusion 3D.nlogo3d *** FAILED ***
[info]   java.lang.IllegalStateException: MethodRipper says: Java class class org.nlogo.prim._breedon not allowed to call method 'breedName' in a report_X()/perform_X() method.
[info]   at org.nlogo.generate.MethodRipper.writeTransformedBytecode(MethodRipper.scala:22)
[info]   at org.nlogo.generate.Generator$InstructionGenerator.generateInstruction(Generator.scala:207)
[info]   at org.nlogo.generate.Generator$InstructionGenerator.$anonfun$generateInstruction$1(Generator.scala:189)
[info]   at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
[info]   at org.nlogo.generate.Generator$InstructionGenerator.generateInstruction(Generator.scala:181)
[info]   at org.nlogo.generate.Generator$InstructionGenerator.generateBodyMethod(Generator.scala:133)
[info]   at org.nlogo.generate.Generator$InstructionGenerator.generate(Generator.scala:111)
[info]   at org.nlogo.generate.Generator.org$nlogo$generate$Generator$$recurse(Generator.scala:29)
[info]   at org.nlogo.generate.Generator.$anonfun$generate$1(Generator.scala:25)
[info]   at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:286)
[info]   ...
```

**Comment by LaCuneta** [comment]
Okay, so the clue I found here was in `_randomconst`, which has to hold a value for the random number to produce:  https://github.com/NetLogo/NetLogo/blob/hexy/netlogo-gui/src/main/prim/_randomconst.scala#L7-L8

It is marked `private[this] val _n: Long`, and then that `_n` variable is what is used in the reporter method.  The same should work here.  I don't think adding the public method is strictly necessary (as `_randomconst` does with `def n = _n`, but it might help in debugging?  In checking the `_breedon` prim itself might also need this change.  Let me know if that helps or you still run into issues.

**Comment by kodingkoning** [comment]
@LaCuneta Thanks for looking at this. However, if `breedName` is private, then the optimization doesn't work, because it doesn't have access to the name of the breed in `AnyBreedOn`. If I do make `breedName` public, then it gets the same problem as not making the `val` private in the first place.

From the error message, I can't tell if it's trying to use the value as a method, or if `MethodRipper` is making some specific check that I don't understand.

**Comment by LaCuneta** [comment]
So, it wouldn't be private in the parser version of `_breedon`, it'd be private in the engine version, the one [that lives here](https://github.com/kodingkoning/NetLogo/blob/e562e020584d395d5c5eb613d77de126cd2025f1/netlogo-core/src/main/prim/_breedon.scala) (moved to `netlogo-core` in this PR).  That shouldn't affect the `AnyBreedOn` optimization class at all, then.

If anything needs access on the engine side, then you can add the `def breedName = _breedName` to allow that.  The key to get it working with the method ripper is to have the value private for the `report_1` method (as in the `_randomconst` example).  I modified the branch locally just to double check and it did appear to work as expected for me.  If you still have trouble, feel free to push the work in progress or post a snippet and I'll see if I can spot what's different.

**Comment by kodingkoning** [comment]
@LaCuneta is the change I added in the most recent commit what you are describing? That is what I tried when I continued to receive the same error.

**Comment by LaCuneta** [comment]
@kodingkoning Okay, I see the issue, the same change needs to be added to the new `_anybreedon` prim, too.  I should've been clearer about that, sorry!  After I added it there, the language and optimizer tests all passed.

**Pull request merged**
